name: Build wheel

on:
  push:
    tags: v*
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.10"
      - name: build onnxruntime
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd onnxruntime
          build.bat --build_shared_lib --enable_pybind --build_wheel --config RelWithDebInfo --parallel --cmake_generator "Visual Studio 17 2022" --skip_tests
      - name: upload artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dist
          path: onnxruntime/build/Windows/RelWithDebInfo/RelWithDebInfo/dist
      - name: release
        uses: "softprops/action-gh-release@v1"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          name: "onnxruntime ${{github.ref_name}}"
          tag_name: "${{github.ref_name}}"
          body: ""
          files: |
            onnxruntime/build/Windows/RelWithDebInfo/RelWithDebInfo/dist/*.whl
